# Generated by Django 4.0.5 on 2022-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity', models.CharField(max_length=10, unique=True, verbose_name='Ідентифікатор')),
                ('name', models.CharField(max_length=100, verbose_name='Найменування')),
            ],
        ),
    ]
