# Generated by Django 4.0.5 on 2022-06-28 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('id',), 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекти'},
        ),
    ]
