# Generated by Django 4.0.5 on 2022-06-28 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_project_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransferInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(max_length=100, verbose_name='Банк')),
                ('mfo', models.CharField(max_length=6, verbose_name='МФО')),
                ('account', models.CharField(max_length=29, verbose_name='Рахунок')),
                ('edrpou', models.CharField(max_length=10, verbose_name='Код за ЄДРПОУ')),
                ('payee', models.CharField(max_length=100, verbose_name='Отримувач')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='pages.project', verbose_name='Проект')),
            ],
            options={
                'verbose_name': 'Реквізит банківського переводу',
                'verbose_name_plural': 'Реквізити банківського переводу',
                'ordering': ('id',),
            },
        ),
    ]
