# Generated by Django 4.0.5 on 2022-06-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_project_name_en'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsituentsDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Найменування')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='Найменування (англ.)')),
                ('file', models.FileField(upload_to='consituents_docs', verbose_name='Файл')),
                ('type', models.CharField(choices=[('pdf', 'pdf')], max_length=3, verbose_name='Тип файлу')),
            ],
            options={
                'verbose_name': 'Установчий документ',
                'verbose_name_plural': 'Установчи документи',
                'ordering': ('id',),
            },
        ),
    ]
