# Generated by Django 4.0.5 on 2022-06-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_consituentsdocs'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='disabled',
            field=models.BooleanField(blank=True, default=False, verbose_name='Відключено'),
        ),
    ]
