# Generated by Django 4.0.5 on 2022-06-29 14:19

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('pages', '0006_project_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addr', models.TextField(blank=True, default=None, null=True, verbose_name='Адреса')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, verbose_name='Телефон')),
                ('facebook', models.URLField(blank=True, default=None, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, default=None, null=True, verbose_name='Instagram')),
                ('talagram', models.URLField(blank=True, default=None, null=True, verbose_name='Telegram')),
                ('email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='Сайт')),
            ],
            options={
                'verbose_name': 'Адреса компанії',
                'verbose_name_plural': 'Адреси компанії',
                'ordering': ('id',),
            },
        ),
    ]
