# Generated by Django 4.0.5 on 2022-06-29 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('pages', '0007_addresses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addresses',
            name='site',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='sites.site', verbose_name='Сайт'),
        ),
    ]
