# Generated by Django 4.0.5 on 2022-06-30 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_addresses_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addresses',
            old_name='talagram',
            new_name='telegram',
        ),
    ]
