# Generated by Django 4.0.5 on 2022-07-01 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_rename_talagram_addresses_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cardURL',
            field=models.URLField(blank=True, default=None, null=True, verbose_name="Адреса платіжної системи для 'credit-card'"),
        ),
        migrations.AddField(
            model_name='project',
            name='cryptoURL',
            field=models.URLField(blank=True, default=None, null=True, verbose_name="Адреса платіжної системи для 'crypto'"),
        ),
    ]
