# Generated by Django 4.0.5 on 2022-07-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_project_cardurl_project_cryptourl'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferinfo',
            name='name',
            field=models.CharField(default='Без назви', max_length=60, verbose_name='Найменування'),
            preserve_default=False,
        ),
    ]
