# Generated by Django 4.0.5 on 2022-07-02 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_banktransferinfo_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferinfo',
            name='purpose',
            field=models.TextField(default='', verbose_name='Призначення платежу'),
            preserve_default=False,
        ),
    ]
