# Generated by Django 4.0.5 on 2022-07-02 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_banktransferinfo_beneficiary_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addresses',
            name='addr_en',
            field=models.TextField(blank=True, default=None, null=True, verbose_name='Адреса (англ.)'),
        ),
    ]
