# Generated by Django 4.0.5 on 2022-07-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0015_addresses_addr_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransferinfo',
            name='currency',
            field=models.CharField(choices=[('UAH', 'UAH'), ('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP')], default='UAH', max_length=3, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
