# Generated by Django 4.0.5 on 2022-07-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_banktransferinfo_beneficiary_bank'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(verbose_name='Завантажено')),
                ('file', models.FileField(upload_to='reports', verbose_name='Звіт')),
            ],
            options={
                'verbose_name': 'Фінансовий звіт',
                'verbose_name_plural': 'Фінансові звіти',
                'ordering': ('-uploaded_at',),
            },
        ),
    ]
