# Generated by Django 4.0.5 on 2022-07-05 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_financialreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialreport',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Завантажено'),
        ),
    ]
