# Generated by Django 4.0.5 on 2022-07-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_banktransferinfo_iban_alter_banktransferinfo_bic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransferinfo',
            name='correspondent_bank_bic',
            field=models.CharField(blank=True, default=None, max_length=8, null=True, verbose_name='Correspondent bank (SWIFT)'),
        ),
    ]
